### ISSUE TITLE
vimeo black bars

### ISSUE THREAD

**Issue by ronlobo** [davatron5000/FitVids.js#130]
Hi,

I can see a black background on top of the vimeo iframe.
Any chance to remove it or change the background to another color?

Thanks

**Comment by KeeyaWangJones** [comment]
I created a solution for this exact problem using a portion of the above css. If you add a "width by vw" it will size consistently on any monitor/device.   I added a margin so that the iframe will stay centered in the div once the width is shorter. 
#myvimeoiframeID {
  height: 112%;
  width: 80vw;
  margin: 0px 15% auto;
}

**Comment by leoj3n** [comment]
@KeeyaWangJones Great, glad you figured out a solution for yourself. I don't think `vw` was a viable option back in 2013.
