### ISSUE TITLE
FitVids destroy method

### ISSUE THREAD

**Issue by frankie-loves-jesus** [davatron5000/FitVids.js#138]
Is there a way to disable FitVids on items it's already been initialized on?

**Comment by WebDevCA** [comment]
The use case for me is that I have been assigned to work on a WordPress site that I did not create. FitVid is forcing some videos to display larger than the client wants them to be. And it seems to be partly due to the overall lameness of WordPress making it hard to know if all your DIVs and other elements are nested correctly. It appears that the video thinks it's in a larger box than it should be.

**Comment by davatron5000** [comment]
Hard to diagnose anything without a reduced test case of the problem at hand. And what is does “larger” mean in this context? FitVids sets up an aspect ratio rectangle and the video embed fills that rectangle.

Any code that can replicate the issue helps figure it out.

________________________________

**Comment by jarodium** [comment]
Still, a destroy method can be useful.
My use case is that I have an invisible tab that I want to show later on. I'll have to do destroy it manually.
