### ISSUE TITLE
Ignore With Class doesn't work with ClickToFlash

### ISSUE THREAD

**Issue by michaellindahl** [davatron5000/FitVids.js#207]
When ClickToFlash is disabled–the element (video/flash content) is loaded with the page–Ignore With Class does it's job and ignores the element. However, when ClickToFlash is enabled and the element is loaded after the page has been loaded, Ignore With Class no longer causes FitVids to ignore the element and the element is then has an undesired fluid width.

**Comment by kenhowardpdx** [comment]
Hey Michael. You'll need to configure FitVids to fire after ClickToFlash content has loaded.

```
setTimeout(loadFitVids, 1000);

function loadFitVids () {
  $('.fitVids').fitVids();
}
```

Closing as this is not a limitation of FitVids.

**Comment by michaellindahl** [comment]
Are you sure? I feel like this requires me to loadFitVids only after a user has clickToFlash-ed the content. It would appear this means I need to decide how long to wait. Before that determined period of time the fitVids is not in effect, and if the user clicksToFlash after that period of time the issue persists. Am I correct here?
This would also mean that this effects all users going to the site, not just those with ClickToFlash enabled. To me this seems like a really poor solution.

**Comment by kenhowardpdx** [comment]
All I can say is ClickToFlash is altering the content of the page at the same time as FitVids, so there's likely some collisions occurring. I don't have experience with ClickToFlash so can't be certain what is happening. Maybe ClickToFlash has registered events that you can watch for and then call the loadFitVids function when ClickToFlash is finished.

**Comment by davatron5000** [comment]
We ran into this issue with Safari's HTML5 YouTube extension (#2). Simply put, browser extensions that perform aggressive customizations are really tricky to work with and hella hard to debug.

I think what's happening is FitVids is trying to run, but since ClickToFlash has already fun, it doesn't know there are any videos available on the page. Unless they supply an browser event or some such thing that we could listen for, we could possibly accommodate that. But that's not documented and there's not much we can do with it.

Unfortunately I have to file it as: **Can't Fix**
