### ISSUE TITLE
Add MIT/GPL license

### ISSUE THREAD

**Issue by mattmischuk** [davatron5000/FitVids.js#212]
The current license isn't clear that it separates you from liability, which is what most permissive licenses do.

**Comment by Smitevils** [comment]
Hello.I do not quite understand what you mean. I do not know very well the technical English. Can you describe in more detail?

**Comment by mattmischuk** [comment]
@smitevils I've request a license change to a clearer more explicit one. MIT or GPL licenses describe liability better.

**Comment by davatron5000** [comment]
I feel WTFPL is pretty clear http://www.wtfpl.net/about/ - it's worked thus far.

I'm fine to switch to MIT/GPL dual license but that's possibly a huge shift since this is being used by hundreds of thousands of sites. @mattmischuk do you have any experience in changing a license? Is there an internal legal issue you were running into?

**Comment by mattmischuk** [comment]
I agree that this is very clear (in a humorous way), however certain companies have policies that only accept whitelisted licenses. I have not changed a OSS project's license so I wouldn't know.

That being said, since this issue is from 2015 and nobody else has seemed to make a claim that the license needs to change I would close it.

Thanks for following up.
