### ISSUE TITLE
Fitvids errors with Wordpress 4.5

### ISSUE THREAD

**Issue by JohanDH** [davatron5000/FitVids.js#234]
Hi,

I get fitvids errors in the console with jquery 1.12 en jquery migrate in Wordpress 4.5 > fitvids is not a function. Any idea why this happens?

**Comment by JohanDH** [comment]
I discovered that with W3T cache "Page cache Disk enhanced" deactivated the fitvids plugin works. With the page cache activated, fitvids plugin work sometimes.

**Comment by davatron5000** [comment]
`fitvids is not a function` usually means fitvids didn't make it to your page. Three typical culprits in WordPress:

1. Plugins like W3TC will occasionally move scripts around and cause problems. 
1. `jquery` and `jquery.fitvids` get out of order (jquery needs to be first). 
3. `jquery` and `fitvids` are setup perfectly, but another plugin will add in another instace of jquery, wiping out the first one that had fitvids attached to it.

You gotta be a little careful with scripts on WordPress and sometimes viewsource to read the order of what it's spitting out. You'll also need to use `jQuery` instead of `$` if you're writing stuff yourself.

I recommend checking out this site:

http://fixingthesejquery.com/#slide1

It's a good "How to fix jQuery when things go wrong" tutorial. Also has some WordPress specific bugs. Best of luck, keep hacking away!

**Comment by Pls** [comment]
HTML minify plugin also is conflicting with fitvids wordpress plugin. Maby this helps for someone debugging.
