### ISSUE TITLE
FitVid adding unnecessary padding to my video embeds.

### ISSUE THREAD

**Issue by nativeimaging** [davatron5000/FitVids.js#237]
Why this method actually works better. 
http://jaydenseric.com/blog/responsive-iframes

**Comment by davatron5000** [comment]
Sorry, is this the same issue as #236, just with a different title?

**Comment by nativeimaging** [comment]
No, i'm pointing out that your script is broken.

**Comment by nativeimaging** [comment]
Shame, but I have to manually remove all packages & plugins who use this script, causing me a lot of lost time and damage control. Should I have to go to each author with this issue to convince them to stop using your script? Or can you evolve?

**Comment by chriscoyier** [comment]
The method you point out is actually much, much less performant. You're being extremely rude though, so I'm not going to spend any energy explaining it.

**Comment by davatron5000** [comment]
You've probably done enough trolling. Let me respond to that post here and help you understand what this plugin actually does. The article you cited makes 4 key points, and one additional argument.

> 1 Wrappers may not play nice with your current setup. Perhaps your videos are added, sized and positioned via a CMS WYSIWYG.

I'm not sure I understand the problem here but I assume it's for Fixed Width designs and WYSIWYG editors. FitVids is kinda great at making videos dumped into a WYSIWYG responsive.

> 2 Is ~75 lines of jQuery really necessary?

The lines of code are irrelevant. This script solves more problems and has more features that have developed over the past 5 years than the solution you advocate. I could explain and account for why each line of code exists.

> 3 Most implementations stretch videos to fill their container's width, disrespecting any inline dimensions your iframe should have.

This is not the case of FitVids. It's for aspect based resizing.

> 4 Non-semantic wrappers that bloat your inspector suck.

This is just a matter of taste, but utility classes are a pretty common construct. `resize` events have real-world user implications.

## The final argument

> So what if a really crappy PC lags a bit resizing the browser window?

While this may not be one of Jayden's concerns, for a maintainer of a plugin that runs on thousands of sites this is a huge concern. FitVids runs once. Not over and over on resize. "But users don't resize on mobile"? False. Anything that makes the document taller (accordions, tabs, ajax in things) will trigger a document resize. I would argue that a good design for a plugin like this is something that runs once and gets out of the way, not running over and over and over and over at the expense of the User.

Good luck out there. Sorry people find this useful enough to include in their projects and it doesn't meet your personal standards.
