### ISSUE TITLE
Safari player displays extremely tall container

### ISSUE THREAD

**Issue by cmcommons** [davatron5000/FitVids.js#238]
http://traderspointcreamery.com/events/fridays-on-the-farm/

The vimeo video player at the bottom of that page is displaying inside an outrageously tall container in Safari only. I am not sure what is causing the issue.

Help?

**Comment by davatron5000** [comment]
When I open Web Inspector > Console, I see an error that could be affecting fitVids triggering.

```
Syntax error, unrecognized expression: [href=#]
```

In your `main.min.js` you have 

```javascript
jQuery(this).find(".full-video, .video-shortcode, .wooslider .slide-content").fitVids()
```

This should work but I think it's being never getting here because of the previous error. There are quite a few references to `[href=#]` in `main.min.js`, so it's really hard to debug the problem without a reduced test case or unminified code that I can edit (like a CodePen).

My gut says this is an issue with the theme vendor. I'd maybe reach out to them.
