### ISSUE TITLE
Some doubt of "<p>x</p><style>...</style>"?

### ISSUE THREAD

**Issue by FaureWu** [davatron5000/FitVids.js#251]
I have some doubt of src as follow:

why you done it by:
``` JS
      var div = document.createElement("div");
      div.innerHTML = '<p>x</p><style id="fit-vids-style">' + css + '</style>';
      head.appendChild(div.childNodes[1]);
```
but not:
``` JS
    var style = document.createElement('style');
    style.type = 'text/css';
    style.innerHTML= css;
    head.appendChild(style);
```

Is there any metaphysics in it?

**Comment by davatron5000** [comment]
This is an old IE NoScope bug, documented in #144.

Older versions of Internet Explorer don't allow you to append `<style>` tags directly in the `<head>`, so the workaround is to create an element with 2 children, then append the 2nd childNode.

It's mentioned in #159 that we'd probably drop this feature in a 2.0 version of FitVids, but because this plugin is used on a lot of legacy sites, it'd be a breaking change to remove it.
