### ISSUE TITLE
Video height is wrong if width uses calc()

### ISSUE THREAD

**Issue by yratof** [davatron5000/FitVids.js#259]
If you offset a video in your layout:

```
.video {
  margin-left: -5rem;
  width: calc( 100% + 10rem);
}
```

You'll find that the aspect ratio fails to take this into consideration & the video becomes cropped

**Comment by davatron5000** [comment]
Can you make a CodePen or JSBin that shows the issue. Percentage-based padding (how FitVids works) is always based off the width of the parent. So it's possible using negative margins to change the video here just won't work since it'd be based off the parent.

**Comment by yratof** [comment]
Sure thing:

https://codepen.io/yratof/pen/PeGNvK

**Comment by davatron5000** [comment]
Yeah. It's probably not going to work. And not really a FitVids issue so I'll have to close it. FitVids sizes based on the parent. Negative margins to resize the child means it'll never really work. If you think about what the CSS is doing, it's "draw a box this tall, then stretch it left and right" only the left and right sides of the box are getting pulled out of the parent.

One thing you could do is use `:not()` to pad everything except the iframe and fluid-width-video-wrapper. 

https://codepen.io/davatron5000/pen/MGjPMP

Or wrap the iframe in a `<div class="fullwidth">` and do your negative margining on that instead of the `.fluid-width-video-wrapper`
